import { PrototypeProjectViewModel } from "./types";

export const prototypeProject: PrototypeProjectViewModel = {
  id: "preview-world-a",
  name: "北海编年史",
  path: "D:\\Languages\\NorthSea.fishtongue",
  languages: [
    {
      id: "alan",
      name: "阿兰语",
      nativeName: "Ārana",
      family: "北海语系",
      era: "公元前 420—公元 680",
      region: "北海沿岸",
      status: "礼仪语言",
      words: 1284,
      warnings: 3,
      stages: [
        { id: "alan-sacred", name: "圣典时代", years: "前 420—前 80", documentation: "partial" },
        { id: "alan-kings", name: "诸王时期", years: "前 80—340", documentation: "recorded" },
        { id: "alan-late", name: "北迁后期", years: "340—680", documentation: "recorded" },
      ],
    },
    {
      id: "nor",
      name: "诺尔语",
      nativeName: "Nōr",
      family: "北海语系",
      era: "120—至今",
      region: "北方群岛",
      status: "活语言",
      words: 846,
      warnings: 0,
      stages: [],
    },
    {
      id: "saren",
      name: "萨伦语",
      nativeName: "Śaren",
      family: "东陆语系",
      era: "前 210—510",
      region: "萨伦河谷",
      status: "死语言",
      words: 392,
      warnings: 7,
      stages: [
        { id: "saren-old", name: "河谷铭文期", years: "前 210—90", documentation: "partial" },
        { id: "saren-gap", name: "失落世纪", years: "90—260", documentation: "unrecorded" },
        { id: "saren-late", name: "帝国晚期", years: "260—510", documentation: "recorded" },
      ],
    },
    {
      id: "tala",
      name: "塔拉语",
      nativeName: "Tála",
      family: "未分类",
      era: "年代不明",
      region: "西部高原",
      status: "部分记录",
      words: 118,
      warnings: 12,
      stages: [],
    },
  ],
  lexemes: [
    { id: "l1", form: "ama", ipa: "/ˈa.ma/", meaning: "母亲；女性长辈", partOfSpeech: "名词", source: "继承", stage: "诸王时期", confidence: "已确认" },
    { id: "l2", form: "nōr", ipa: "/noːr/", meaning: "海；外海", partOfSpeech: "名词", source: "原生", stage: "诸王时期", confidence: "已确认" },
    { id: "l3", form: "kelan", ipa: "/ˈke.lan/", meaning: "沿岸行走", partOfSpeech: "动词", source: "派生", stage: "北迁后期", confidence: "规则生成" },
    { id: "l4", form: "sava", ipa: "/ˈsa.va/", meaning: "誓言；盟约", partOfSpeech: "名词", source: "借词", stage: "诸王时期", confidence: "人工重构" },
    { id: "l5", form: "ir", ipa: "/ir/", meaning: "向；朝向", partOfSpeech: "介词", source: "继承", stage: "圣典时代", confidence: "已确认" },
  ],
};
